name: Build and test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
      - name: Set up JDK 17
        uses: actions/setup-java@4fe61d24fe5472910b93bdeffb8aad49f979d862
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'maven'
      - name: Build and test with Maven
        run: mvn -e -B clean verify
